production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: <%= (ENV['MONGO_POOL_SIZE']||"300").to_i %>
        heartbeat_frequency: 1
        background_indexing: true
        read:
          mode: <%= ENV['MONGO_READ_MODE']||"primary" %>

development:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
      options:
        max_pool_size: 300
        heartbeat_frequency: 1
        read:
          mode: <%= ENV['MONGO_READ_MODE']||"primary" %>
test:
  clients:
    default:
      uri: mongodb://picap:picap@localhost/picap
